import { useState, useEffect } from 'react';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import cpclLogo from '../assets/cpcl-logo.webp';
import './AppStyles.css';

const ApplicationForm = () => {
    const navigate = useNavigate();
    const [submitMessage, setSubmitMessage] = useState('');
    const [existingApp, setExistingApp] = useState(null);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        const checkExistingApplication = async () => {
            try {
                const token = localStorage.getItem('token');
                const response = await axios.get('http://localhost:8080/api/applications/me', {
                    headers: { 'Authorization': `Bearer ${token}` }
                });
                setExistingApp(response.data);
            } catch (err) {
                // No existing application found, user can proceed to apply
            } finally {
                setIsLoading(false);
            }
        };
        checkExistingApplication();
    }, []);

    const handleDownloadApplication = (e) => {
        e.preventDefault();

        if (!existingApp) {
            alert("No application data found to download!");
            return;
        }

        try {
            const doc = new jsPDF();

            // HEADER SECTION
            doc.setFontSize(18);
            doc.setTextColor(0, 86, 179);
            doc.text("CPCL SPARC SPORTS SCHOLARSHIP 2026", 105, 20, { align: "center" });

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text("Official Application Receipt", 105, 28, { align: "center" });

            doc.setLineWidth(0.5);
            doc.line(20, 34, 190, 34);

            // APPLICATION DETAILS
            doc.setFontSize(14);
            doc.setTextColor(100, 100, 100);
            doc.text("Application Status", 20, 45);

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`Application ID: ${existingApp.id}`, 20, 55);
            doc.text(`Current Status: ${existingApp.status}`, 20, 63);

            // APPLICANT DETAILS
            doc.setFontSize(14);
            doc.setTextColor(100, 100, 100);
            doc.text("Applicant Details", 20, 80);

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`First Name: ${existingApp.firstName}`, 20, 90);
            doc.text(`Last Name: ${existingApp.lastName}`, 20, 98);
            doc.text(`Gender: ${existingApp.gender}`, 20, 106);
            doc.text(`Date of Birth: ${existingApp.dateOfBirth}`, 20, 114);

            // SPORTS CREDENTIALS
            doc.setFontSize(14);
            doc.setTextColor(100, 100, 100);
            doc.text("Sports Credentials", 20, 131);

            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(`Sport: ${existingApp.sportName}`, 20, 141);
            doc.text(`Scholarship Level: ${existingApp.scholarshipLevel}`, 20, 149);
            doc.text(`Tournament Level: ${existingApp.tournamentLevel}`, 20, 157);
            doc.text(`Achievement: ${existingApp.achievement}`, 20, 165);
            doc.text(`Federation Name: ${existingApp.federationName}`, 20, 173);

            // FOOTER
            doc.line(20, 270, 190, 270);
            doc.setFontSize(10);
            doc.setTextColor(150, 150, 150);
            doc.text("Generated by the CPCL SPARC Scholarship Portal", 105, 280, { align: "center" });

            doc.save(`SPARC_Application_${existingApp.id}.pdf`);

        } catch (error) {
            console.error("PDF generation failed:", error);
            alert("An error occurred while generating the PDF document.");
        }
    };

    const handleViewMyDocument = async (docType) => {
        try {
            const token = localStorage.getItem('token');
            const response = await axios.get(`http://localhost:8080/api/documents/me/${docType}`, {
                headers: { 'Authorization': `Bearer ${token}` },
                responseType: 'blob'
            });
            const fileURL = URL.createObjectURL(new Blob([response.data], { type: response.headers['content-type'] }));
            window.open(fileURL, '_blank');
        } catch (err) {
            alert("Document not found.");
        }
    };

    const validationSchema = Yup.object({
        firstName: Yup.string()
            .matches(/^[A-Za-z\s\-]+$/, "Only alphabets, spaces, and hyphens allowed")
            .min(2, "Name is too short")
            .max(50, "Name is too long")
            .required('First name is required'),
        lastName: Yup.string()
            .matches(/^[A-Za-z\s\-]+$/, "Only alphabets, spaces, and hyphens allowed")
            .min(1, "Name is too short")
            .max(50, "Name is too long")
            .required('Last name is required'),
        gender: Yup.string().required('Please select a gender'),
        dateOfBirth: Yup.date().required('Date of Birth is required'),
        sportName: Yup.string().required('Please select a sport'),
        scholarshipLevel: Yup.string().required('Please select a level'),
        tournamentLevel: Yup.string().required('Please select tournament level'),
        achievement: Yup.string()
            .required('Please select your achievement')
            .test('match-level', 'Invalid achievement for selected tier', function (value) {
                const { scholarshipLevel, tournamentLevel } = this.parent;

                if (scholarshipLevel === 'ELITE_SCHOLAR') {
                    if (tournamentLevel === 'INTERNATIONAL' && value === 'PARTICIPATION') return true;
                    if (tournamentLevel === 'NATIONAL' && ['TOP_1_5', 'REPRESENTATION'].includes(value)) return true;
                    return false;
                }
                if (scholarshipLevel === 'SCHOLAR') {
                    if (tournamentLevel === 'STATE' && ['STATE_MEDALIST', 'REPRESENTATION'].includes(value)) return true;
                    if (tournamentLevel === 'NATIONAL' && ['RANK_6_10', 'QUARTER_FINALIST'].includes(value)) return true;
                    return false;
                }
                return true;
            }),
        federationName: Yup.string().required('Federation Name is required')
    });

    const formik = useFormik({
        initialValues: {
            firstName: '', lastName: '', gender: '', dateOfBirth: '',
            sportName: '', scholarshipLevel: '', tournamentLevel: '',
            achievement: '', federationName: ''
        },
        validationSchema: validationSchema,
        onSubmit: async (values) => {
            try {
                const token = localStorage.getItem('token');
                const response = await axios.post('http://localhost:8080/api/applications/submit', values, {
                    headers: {
                        'Authorization': `Bearer ${token}`,
                        'Content-Type': 'application/json'
                    }
                });

                setSubmitMessage("Success! Redirecting to document upload...");

                setTimeout(() => {
                    navigate('/upload', { state: { applicationId: response.data } });
                }, 1500);

            } catch (error) {
                let errorDetail = "Failed to submit application.";

                if (error.response && error.response.data) {
                    if (typeof error.response.data === 'string') {
                        errorDetail = error.response.data;
                    } else {
                        errorDetail = error.response.data.message || JSON.stringify(error.response.data);
                    }
                } else if (error.message) {
                    errorDetail = error.message;
                }

                setSubmitMessage("❌ " + errorDetail);
            }
        }
    });

    if (isLoading) {
        return <h3 style={{ textAlign: 'center', marginTop: '50px', color: '#0056b3' }}>Loading your dashboard...</h3>;
    }

    // --- DASHBOARD VIEW (If application exists) ---
    if (existingApp) {
        return (
            <div className="form-container">
                <div className="header-section">
                    <img src={cpclLogo} alt="CPCL Logo" className="cpcl-logo" />
                    <h2>Application Dashboard</h2>
                    <span style={{
                        padding: '8px 15px',
                        borderRadius: '20px',
                        fontWeight: 'bold',
                        color: 'white',
                        display: 'inline-block',
                        marginTop: '10px',
                        backgroundColor: existingApp.status === 'APPROVED' ? '#28a745' : existingApp.status === 'REJECTED' ? '#dc3545' : '#17a2b8'
                    }}>
                        Status: {existingApp.status}
                    </span>
                </div>

                <div style={{ backgroundColor: '#f8f9fa', padding: '20px', borderRadius: '8px', border: '1px solid #eef2f5', marginBottom: '25px' }}>
                    <h3 style={{ marginTop: 0, color: '#2c3e50', fontSize: '18px' }}>Your Submitted Details</h3>
                    <p style={{ margin: '8px 0' }}><strong>Name:</strong> {existingApp.firstName} {existingApp.lastName}</p>
                    <p style={{ margin: '8px 0' }}><strong>Sport:</strong> {existingApp.sportName} ({existingApp.scholarshipLevel})</p>
                    <p style={{ margin: '8px 0' }}><strong>Achievement:</strong> {existingApp.achievement} at {existingApp.tournamentLevel} level</p>
                    <p style={{ margin: '8px 0' }}><strong>Submitted On:</strong> {existingApp.submittedAt ? new Date(existingApp.submittedAt).toLocaleString() : 'N/A'}</p>
                </div>

                <h3 style={{ color: '#2c3e50', fontSize: '18px', marginBottom: '15px' }}>Your Uploaded Documents</h3>

                <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                    <button onClick={() => handleViewMyDocument('AGE_PROOF')} className="submit-btn" style={{ flex: 1, marginTop: '0', backgroundColor: '#6c757d' }}>Age Proof</button>
                    <button onClick={() => handleViewMyDocument('PERFORMANCE_CERT')} className="submit-btn" style={{ flex: 1, marginTop: '0', backgroundColor: '#6c757d' }}>Certificate</button>
                    <button onClick={() => handleViewMyDocument('PHOTOGRAPH')} className="submit-btn" style={{ flex: 1, marginTop: '0', backgroundColor: '#6c757d' }}>Photograph</button>
                </div>

                <button onClick={(e) => handleDownloadApplication(e)} className="submit-btn" style={{ marginTop: '15px' }}>
                    ⬇ Download Application Receipt (.pdf)
                </button>
            </div>
        );
    }

    // --- APPLICATION FORM VIEW ---
    return (
        <div className="form-container" style={{ maxWidth: '700px' }}>
            <div className="header-section">
                <img src={cpclLogo} alt="CPCL Logo" className="cpcl-logo" />
                <h2>Scholarship Application</h2>
                <p>Complete your official details below</p>
            </div>

            <form onSubmit={formik.handleSubmit}>

                {/* 1. Personal Details Section */}
                <h3 style={{ color: '#0056b3', borderBottom: '2px solid #eef2f5', paddingBottom: '8px', marginBottom: '20px' }}>1. Personal Details</h3>

                <div style={{ display: 'flex', gap: '15px' }}>
                    <div className="form-group" style={{ flex: 1 }}>
                        <label>First Name</label>
                        <input type="text" placeholder="Enter first name" {...formik.getFieldProps('firstName')} />
                        {formik.touched.firstName && formik.errors.firstName ? <span className="error-text">{formik.errors.firstName}</span> : null}
                    </div>
                    <div className="form-group" style={{ flex: 1 }}>
                        <label>Last Name</label>
                        <input type="text" placeholder="Enter last name" {...formik.getFieldProps('lastName')} />
                        {formik.touched.lastName && formik.errors.lastName ? <span className="error-text">{formik.errors.lastName}</span> : null}
                    </div>
                </div>

                <div style={{ display: 'flex', gap: '15px' }}>
                    <div className="form-group" style={{ flex: 1 }}>
                        <label>Gender</label>
                        <select {...formik.getFieldProps('gender')}>
                            <option value="">Select Gender</option>
                            <option value="MALE">Male</option>
                            <option value="FEMALE">Female</option>
                        </select>
                        {formik.touched.gender && formik.errors.gender ? <span className="error-text">{formik.errors.gender}</span> : null}
                    </div>
                    <div className="form-group" style={{ flex: 1 }}>
                        <label>Date of Birth</label>
                        <input type="date" {...formik.getFieldProps('dateOfBirth')} />
                        {formik.touched.dateOfBirth && formik.errors.dateOfBirth ? <span className="error-text">{formik.errors.dateOfBirth}</span> : null}
                    </div>
                </div>

                {/* 2. Sports & Achievements Section */}
                <h3 style={{ color: '#0056b3', borderBottom: '2px solid #eef2f5', paddingBottom: '8px', marginTop: '30px', marginBottom: '20px' }}>2. Sports & Achievements</h3>

                <div className="form-group">
                    <label>Sport</label>
                    <select {...formik.getFieldProps('sportName')}>
                        <option value="">Select Sport</option>
                        <option value="KABADDI">Kabaddi</option>
                        <option value="KHO_KHO">Kho-Kho</option>
                        <option value="BADMINTON">Badminton</option>
                        <option value="TABLE_TENNIS">Table Tennis</option>
                        <option value="SILAMBAM">Silambam</option>
                        <option value="ATHLETICS">Athletics</option>
                        <option value="BOXING">Boxing</option>
                        <option value="CHESS">Chess</option>
                    </select>
                    {formik.touched.sportName && formik.errors.sportName ? <span className="error-text">{formik.errors.sportName}</span> : null}
                </div>

                <div style={{ display: 'flex', gap: '15px' }}>
                    <div className="form-group" style={{ flex: 1 }}>
                        <label>Scholarship Level</label>
                        <select {...formik.getFieldProps('scholarshipLevel')}>
                            <option value="">Select Level</option>
                            <option value="ELITE_SCHOLAR">Elite Scholar</option>
                            <option value="SCHOLAR">Scholar</option>
                        </select>
                        {formik.touched.scholarshipLevel && formik.errors.scholarshipLevel ? <span className="error-text">{formik.errors.scholarshipLevel}</span> : null}
                    </div>

                    <div className="form-group" style={{ flex: 1 }}>
                        <label>Tournament Level</label>
                        <select {...formik.getFieldProps('tournamentLevel')} disabled={!formik.values.scholarshipLevel}>
                            <option value="">Select Tournament Level</option>
                            {formik.values.scholarshipLevel === 'ELITE_SCHOLAR' && (
                                <>
                                    <option value="INTERNATIONAL">International</option>
                                    <option value="NATIONAL">National</option>
                                </>
                            )}
                            {formik.values.scholarshipLevel === 'SCHOLAR' && (
                                <>
                                    <option value="NATIONAL">National</option>
                                    <option value="STATE">State</option>
                                </>
                            )}
                        </select>
                        {formik.touched.tournamentLevel && formik.errors.tournamentLevel ? <span className="error-text">{formik.errors.tournamentLevel}</span> : null}
                    </div>
                </div>

                <div className="form-group">
                    <label>Highest Achievement</label>
                    <select {...formik.getFieldProps('achievement')} disabled={!formik.values.tournamentLevel}>
                        <option value="">Select Achievement</option>
                        {/* Elite Scholar Options */}
                        {formik.values.scholarshipLevel === 'ELITE_SCHOLAR' && formik.values.tournamentLevel === 'INTERNATIONAL' && (
                            <option value="PARTICIPATION">International Participation</option>
                        )}
                        {formik.values.scholarshipLevel === 'ELITE_SCHOLAR' && formik.values.tournamentLevel === 'NATIONAL' && (
                            <>
                                <option value="TOP_1_5">Top 1-5 Ranking</option>
                                <option value="REPRESENTATION">National Representation</option>
                            </>
                        )}
                        {/* Scholar Options */}
                        {formik.values.scholarshipLevel === 'SCHOLAR' && formik.values.tournamentLevel === 'NATIONAL' && (
                            <>
                                <option value="RANK_6_10">Rank 6-10</option>
                                <option value="QUARTER_FINALIST">Quarter-Finalist</option>
                            </>
                        )}
                        {formik.values.scholarshipLevel === 'SCHOLAR' && formik.values.tournamentLevel === 'STATE' && (
                            <>
                                <option value="STATE_MEDALIST">State Medalist</option>
                                <option value="REPRESENTATION">State Representation</option>
                            </>
                        )}
                    </select>
                    {formik.touched.achievement && formik.errors.achievement ? <span className="error-text">{formik.errors.achievement}</span> : null}
                </div>

                <div className="form-group">
                    <label>Federation Name</label>
                    <input type="text" {...formik.getFieldProps('federationName')} placeholder="e.g. Athletics Federation of India" />
                    {formik.touched.federationName && formik.errors.federationName ? <span className="error-text">{formik.errors.federationName}</span> : null}
                </div>

                <button type="submit" className="submit-btn" style={{ marginTop: '20px' }}>
                    Submit Application
                </button>
            </form>

            {/* Dynamic Submission Messages */}
            {submitMessage && (
                <div className={submitMessage.includes('Success') ? 'success-text' : 'error-text'} style={{ marginTop: '20px' }}>
                    {submitMessage}
                </div>
            )}
        </div>
    );
};

export default ApplicationForm;